const countries = [
	"afghanistan", "kabul",
	"albania",
	"algeria", "algiers",
	"andorra", "andorra la vella",
	"angola", "launda",
	"anguilla",
	"antarctica",
	"antigua",
    "antigua and barbuda",
	"argentina", "buenos aries",
	"armenia",
	"australia", "canberra", "sydney", "perth",
	"austria", "vienna",
	"azerbaijan",
	"bahamas",
	"bahrain",
	"bangladesh", "dhaka",
	"barbados",
	"belarus", "minsk",
	"belgium",  "brussels",
	"belize", 
	"benin",
	"bermuda",
	"bhutan", "thimpu",
	"bolivia", "la paz",
	"bonaire", 
	"bosnia and herzegovina", "sarajevo",
	"botswana",
	"bouvet island",                                                                                        
	"brazil", "brasillia", "rio de janerio", 
	"british indian ocean territory",
	"brunei",
	"bulgaria", "sophia",
	"burkina faso",
	"burundi", 
	"cabo verde",
	"cambodia", "phnom penh",
	"cameroon", 
	"canada", "ottowa", "toronto",
	"cayman islands",
	"central african republic",
	"chad",
	"chile", "santiago",
	"china", "bejing", "shanghai", "guangzhou",
	"christmas island",
	"cocos island",
	"colombia", "bogota",
	"comoros",
	"democratic republic of congo", "khinshasa",
	"congo",
	"cook islands",
	"costa rica",
	"croatia",
	"cuba", "havana",
	"curacao",
	"cyprus",
	"czechia", "prague",
	"cote d'ivoire",
	"denmark", "kopenhagen", "copenhagen",
	"djibouti",
	"dominica",
	"dominican republic",
	"ecuador",
	"egypt", "cairo", "alexandria",
	"el salvador", "salvador",
	"equatorial guinea",
	"eriteria",
	"estonia", "talinn",
	"eswantini",
	"ethiopia", "addis ababa",
	"falkland islands",
	"faroe islands",
	"fiji",
	"finland", "helsinki",
	"france", "paris", "lyon", "marsielle",
	"french guiana",
	"french polynesia",
	"french southern territories",
	"gabon",
	"gambia",
	"georgia", "tbillisi",
	"germany", "berlin", "hamburg", "frankfurt", "munich",
	"ghana",
	"gibraltar",
	"greece",
	"greenland",
	"grenada",
	"guadeloupe",
	"guam",
	"guatemala",
	"guernsey",
	"guinea",
	"guinea bissau",
	"guyana",
	"haiti",
	"holy see",
    "vatican city", 
	"honduras",
	"hong kong",
	"hungary", "budapest",
	"iceland", 
	"india", "delhi", "mumbai", "chennai", "ahemdabad", "zirakpur", "gokak", "bangalore", "hyderabad", "bhuhaneswar",
    "indonesia", "jakarta",
	"iran", "tehran",
	"iraq", "baghdad",
	"ireland", "dublin",
	"isle of man",
	"israel", 
	"italy", "rome", "venice", "napels",
	"jamaica",
	"japan", "tokyo", "osaka",
	"jersey",
	"jordan", "amman",
	"kazakhstan", 
	"kenya", "nairobi",
	"kiribati",
	"north korea", "pyongyang",
	"south korea", "souel",
	"kuwait", "kuwait city",
	"kyrgyzstan",
	"lao",
	"latvia",
	"lebanon", "beirut",
	"lesotho",
	"liberia",
	"libya",
	"liechtenstein",
	"lithuania",
	"luxembourg",
	"macao",
	"madagascar",
	"malawi",
	"malaysia",
	"maldives",
	"mali",
	"malta",
	"marshall islands",
	"martinique",
	"mauritana",
	"mauritius",
	"mayotte",
	"mexico",
	"micronesia",
	"moldova",
	"monaco",
	"mongolia",
	"montenegro",
	"montserrat",
	"morocco",
	"mozambique",
	"myanmar",
	"namibia",
	"nauru",
	"nepal",
	"netherlands",
	"new caledonia",
	"new zealand",
	"nicaragua",
	"niger",
	"nigeria",
	"niue",
	"norfolk island",
	"northern mariana islands",
    "north macedonia",
	"norway",
	"oman",
	"pakistan",
	"palau",
	"palestine",
	"panama",
	"papua new guinea",
	"paraguay",
	"peru",
	"philippines",
	"pitcairn",
	"poland",
	"portugal",
	"puerto rico",
	"qatar",
	"North Macedonia",
	"romania",
	"russia",
	"rwanda",
	"reunion",
	"saint barthelemy",
	"saint helena",
	"saint kitts and nevis",
	"saint lucia",
	"saint martin",
	"saint pierre",
	"saint vincent and the grenadines",
	"samoa",
	"san marino",
	"sao tome and principe",
	"saudi arabia",
	"senegal",
	"serbia",
	"seychelles",
	"sierra leone",
	"singapore",
	"sint maarten",
	"slovakia",
	"slovenia",
	"solomon islands",
    "somalia",
    "south africa",
    "south georgia and the south sandwich islands",
    "south sudan",
    "spain",
    "sri lanka",
    "sudan",
    "suriname",
    "svalbard",
    "sweden",
    "switzerland",
    "syria",
    "taiwan",
    "tajikistan",
    "tanzania",
    "thailand",
    "timor leste",
    "togo",
    "tokelau",
    "tonga",
    "trinidad and tobago",
    "tunisia",
    "turkey",
    "turkmenistan",
    "turks and caicos islands",
    "tuvalu",
    "uganda",
    "ukraine",
    "united arab emirates",
    "united kingdom",
    "uk",
    "usa",
    "united states of america",
    "uruguay",
    "uzbekistan",
    "vanuatu",
    "venezuela",
    "vietnam",
    "virgin islands",
    "wallis and futuna",
    "western sahara",
    "yemen",
    "zambia",
    "zimbabwe",
    "aland islands"
]

// const alphabet = [
   //  'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'p', 'r', 's', 't', 'u', 'v'
// ]

const inputField = document.querySelector('.input')
const letterDisplay = document.querySelector('.letter')
const statusDisplay = document.querySelector('.status')
const choosenCountryName = document.querySelector('.country-name')
const guessedCountriesDisplay = document.querySelector('.countries-guessed')

let countriesGuessed = JSON.parse(localStorage.getItem('countriesGuessed'))
guessedCountriesDisplay.innerText = countriesGuessed

let letter = 's'

let usedCountries = []

inputField.addEventListener('input', () => {
    enteredCountryName = inputField.value.toLowerCase()
    if (enteredCountryName[0] == letter && countries.includes(enteredCountryName) && !usedCountries.includes(enteredCountryName)) {
        // letter = alphabet[Math.floor(Math.random() * 20)]'
        letter = enteredCountryName[enteredCountryName.length - 1]
        letterDisplay.innerText = letter
        usedCountries.push(enteredCountryName)
        inputField.value = ''
        countriesGuessed += 1
        localStorage.setItem('countriesGuessed', JSON.stringify(countriesGuessed))
        guessedCountriesDisplay.innerText = countriesGuessed
    } else if (enteredCountryName[0] == letter && usedCountries.includes(enteredCountryName)) {
        statusDisplay.innerText = 'country name already used!'
        setTimeout(() => {statusDisplay.innerText = ''; inputField.value = ''}, 1000)
    }
});


